ln5644: ln5644.o Timer.o LN5644.o Arduino.o 
	gcc -o ln5644 ln5644.o Timer.o LN5644.o Arduino.o 

ln5644.o: ln5644.cpp
	gcc -c ln5644.cpp

Timer.o: Timer.cpp
	gcc -c Timer.cpp

LN5644.o: LN5644.cpp
	gcc -c LN5644.cpp

Arduino.o: Arduino.cpp
	gcc -c Arduino.cpp
